#!/usr/bin/env perl
use Mojolicious::Lite -signatures;
use File::Find;
use File::Slurp;

# Helper function to read video mappings
sub read_video_mappings {
    my %mappings;
    open my $fh, '<', 'videos' or die "Cannot open videos file: $!";
    while (my $line = <$fh>) {
        chomp $line;
        my ($key, $url) = split /\s+/, $line, 2;
        $mappings{$key} = $url;
    }
    close $fh;
    return \%mappings;
}

my $video_mappings = read_video_mappings();

get '/' => sub ($c) {
    $c->render(template => 'index');
};

post '/search' => sub ($c) {
    my $search_term = $c->param('search_term');
    my @results;

    find(
        {
            wanted => sub {
                return unless -f;
                return unless /\.txt$/;
                my $file = $File::Find::name;
                my @lines = read_file($file);
                for my $line_num (0 .. $#lines) {
                    if ($lines[$line_num] =~ /$search_term/i) {
                        my $highlighted_line = $lines[$line_num];
                        $highlighted_line =~ s/($search_term)/<mark>$1<\/mark>/gi;
                        my ($video_key) = $file =~ m{analysis/(.+)\.txt};
                        push @results, {
                            file => $file,
                            line_num => $line_num + 1,
                            line => $highlighted_line,
                            video_url => $video_mappings->{$video_key} // '',
                        };
                    }
                }
            },
            no_chdir => 1,
        },
        'analysis'
    );

    $c->render(json => \@results);
};

app->start;

__DATA__

@@ index.html.ep
<!DOCTYPE html>
<html>
<head>
    <title>Video Search</title>
    <style>
        .result { margin-bottom: 20px; }
        .video-player { margin-top: 10px; }
        .suggested-search { cursor: pointer; color: blue; text-decoration: underline; margin-right: 10px; }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#search-form').submit(function(e) {
                e.preventDefault();
                var searchTerm = $('#search-term').val();
                $.post('/search', {search_term: searchTerm}, function(data) {
                    var resultsHtml = '';
                    data.forEach(function(result) {
                        resultsHtml += '<div class="result">';
                        resultsHtml += '<p>' + result.file + ' (Line ' + result.line_num + '): ' + result.line + '</p>';
                        if (result.video_url) {
                            resultsHtml += '<div class="video-player">';
                            resultsHtml += '<iframe width="560" height="315" src="https://www.youtube.com/embed/' + result.video_url.split('v=')[1] + '" frameborder="0" allowfullscreen></iframe>';
                            resultsHtml += '</div>';
                        }
                        resultsHtml += '</div>';
                    });
                    $('#results').html(resultsHtml);
                });
            });

            $('.suggested-search').click(function() {
                var searchTerm = $(this).text();
                $('#search-term').val(searchTerm);
                $('#search-form').submit();
            });
        });
    </script>
</head>
<body>
    <h1>Video Search</h1>
    <div>
        <span class="suggested-search">toys</span>
        <span class="suggested-search">programming</span>
        <span class="suggested-search">lathe</span>
        <span class="suggested-search">terminal</span>
        <span class="suggested-search">debugging</span>
        <span class="suggested-search">ui</span>
    </div>
    <form id="search-form">
        <input type="text" id="search-term" name="search_term" placeholder="Enter search term">
        <input type="submit" value="Search">
    </form>
    <div id="results"></div>
</body>
</html>
